<a href="https://colab.research.google.com/github/zaima-sohail/Deep_learning_projects/blob/main/Backpropagation_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

In [26]:
import pandas as pd

In [27]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['CGPA','Profile_score','LPA'])

In [28]:
df

   CGPA  Profile_score  LPA
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [29]:
def initalize_parameters(layers_dim):
  np.random.seed(3)
  parameters={}
  L=len(layers_dim)
  for l in range(1,L):
    parameters['w'+str(l)] = np.ones((layers_dim[l-1], layers_dim[l])) * 0.1
    parameters['b'+str(l)] = np.zeros((layers_dim[l], 1))
  return parameters

In [30]:
initalize_parameters([2,2,1])

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [31]:
def linear_forward(A_prev,w,b):
  y_pred=np.dot(w.T,A_prev)+b
  return y_pred

In [32]:
def forward_propragation(X,parameters):
   A=X
   L=len(parameters)//2
   A1_output = None # To store the activation of the first layer

   for l in range(1,L+1):
    A_prev=A
    w1=parameters['w'+str(l)]
    b1=parameters['b'+str(l)]

    print("A"+str(l-1)+": ", A_prev)
    print("W"+str(l)+": ", w1)
    print("b"+str(l)+": ", b1)

    A = linear_forward(A_prev, w1, b1)

    if l == 1:
        A1_output = A # Store A after the first layer

    print("A"+str(l)+": ", A)
    print("-"*20)
   return A, A1_output # Return both the final activation and A1

In [33]:
X=df[['CGPA','Profile_score']].values[0].reshape(2,1)
y=df['LPA'].values[0]

In [34]:


y

np.int64(4)

In [35]:
parameters = initalize_parameters([2,2,1])
y_hat,A1=forward_propragation(X,parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
A1:  [[1.6]
 [1.6]]
--------------------
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
A2:  [[0.32]]
--------------------

In [36]:
loss_function=(y-0.32)**2

In [37]:
loss_function

np.float64(13.5424)

now only find the gradient descent

In [38]:
y_hat

array([[0.32]])

In [39]:
A1

array([[1.6],
       [1.6]])

In [42]:
def update_parameters(parameters, y, y_hat, A1, X):

    # Update for W2
    parameters['w2'][0][0] = parameters['w2'][0][0] + \
        (0.001 * 2 * (y - y_hat) * A1[0][0])

    parameters['w2'][1][0] = parameters['w2'][1][0] + \
        (0.001 * 2 * (y - y_hat) * A1[1][0])

    # Update for b2
    parameters['b2'][0][0] = parameters['b2'][0][0] + \
        (0.001 * 2 * (y - y_hat))


    # Update for W1 (first component)
    parameters['w1'][0][0] = parameters['w1'][0][0] + \
        (0.001 * 2 * (y - y_hat) * parameters['w2'][0][0] * X[0][0])

    parameters['w1'][1][0] = parameters['w1'][1][0] + \
        (0.001 * 2 * (y - y_hat) * parameters['w2'][0][0] * X[1][0])

    # Update for b1 (first component)
    parameters['b1'][0][0] = parameters['b1'][0][0] + \
        (0.001 * 2 * (y - y_hat) * parameters['w2'][0][0])

    # Update for W1 (second component)
    parameters['w1'][0][1] = parameters['w1'][0][1] + \
        (0.001 * 2 * (y - y_hat) * parameters['w2'][1][0] * X[0][0])

    parameters['w1'][1][1] = parameters['w1'][1][1] + \
        (0.001 * 2 * (y - y_hat) * parameters['w2'][1][0] * X[1][0])

    # Update for b1 (second component)
    parameters['b1'][1][0] = parameters['b1'][1][0] + \
        (0.001 * 2 * (y - y_hat) * parameters['w2'][1][0])

In [43]:
update_parameters(parameters, y, y_hat, A1, X)

/tmp/ipykernel_1657/3397916217.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w2'][0][0] = parameters['w2'][0][0] + \
/tmp/ipykernel_1657/3397916217.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w2'][1][0] = parameters['w2'][1][0] + \
/tmp/ipykernel_1657/3397916217.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['b2'][0][0] + \
/tmp/ipykernel_1657/3397916217.py:16: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w1'][0][0] = parameters['w1'][0][0] + \
/tmp/ipykernel_1657/3397916217.py:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w1'][1][0] = parameters['w1'][1][0] + \
/tmp/ipykernel_1657/3397916217.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b1'][0][0] = parameters['b1'][0][0] + \
/tmp/ipykernel_1657/3397916217.py:27: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w1'][0][1] = parameters['w1'][0][1] + \
/tmp/ipykernel_1657/3397916217.py:30: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w1'][1][1] = parameters['w1'][1][1] + \
/tmp/ipykernel_1657/3397916217.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b1'][1][0] = parameters['b1'][1][0] + \

In [44]:
parameters

{'w1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'w2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

Now, we implement same dataset by python library keras that by imported tensorflow

In [45]:
import pandas as pd

In [46]:
import numpy as np

In [47]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['CGPA','Profile_score','LPA'])

In [48]:
df

   CGPA  Profile_score  LPA
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [50]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [51]:
model=Sequential()

In [53]:
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [54]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [59]:
model.get_weights()

[array([[ 0.3789233, -1.1927695],
        [-0.6469922,  1.1951219]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.4747101 ],
        [-0.84187454]], dtype=float32),
 array([0.], dtype=float32)]

In [62]:
new_weights = [np.array([[0.1, 0.1],
                          [0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1],
                          [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

model.set_weights(new_weights)

model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [63]:
model.set_weights(new_weights)

In [64]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [65]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)

In [66]:
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [73]:
X = df.iloc[:, 0:-1].values.astype(np.float32)   # CGPA, Profile_score
y = df['LPA'].values.astype(np.float32).reshape(-1, 1)   # LPA, reshaped to (num_samples, 1)

history = model.fit(X, y, epochs=75, verbose=1)

Epoch 1/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 768ms/step - loss: 25.8536
Epoch 2/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 25.7639
Epoch 3/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 25.6653
Epoch 4/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 25.5595
Epoch 5/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 25.4476
Epoch 6/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 25.3306
Epoch 7/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 25.2093
Epoch 8/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 25.0843
Epoch 9/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 24.9561
Epoch 10/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 24.8251
Epoch 11/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 24.6916
Epoch 12/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 24.5560
Epoch 13/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 24.4184
Epoch 14/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 24.2792
Epoch 15/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 24.1385
Epoch 16/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 23.9965
Epoch 17/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 23.8533
Epoch 18/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 23.7090
Epoch 19/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 23.5637
Epoch 20/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 23.4176
Epoch 21/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 23.2706
Epoch 22/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 23.1230
Epoch 23/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 22.9747
Epoch 24/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 22.8257
Epoch 25/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 22.6762
Epoch 26/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 22.5262
Epoch 27/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 22.3758
Epoch 28/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 22.2249
Epoch 29/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 22.0736
Epoch 30/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 21.9219
Epoch 31/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 21.7699
Epoch 32/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 21.6175
Epoch 33/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 21.4649
Epoch 34/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 21.3119
Epoch 35/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 21.1587
Epoch 36/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 21.0053
Epoch 37/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 20.8517
Epoch 38/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 20.6978
Epoch 39/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 20.5437
Epoch 40/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 20.3895
Epoch 41/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 20.2351
Epoch 42/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 20.0805
Epoch 43/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 19.9259
Epoch 44/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 19.7710
Epoch 45/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 19.6161
Epoch 46/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 19.4611
Epoch 47/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 19.3060
Epoch 48/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 19.1508
Epoch 49/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 18.9956
Epoch 50/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 18.8403
Epoch 51/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 18.6850
Epoch 52/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 18.5297
Epoch 53/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 18.3744
Epoch 54/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 18.2191
Epoch 55/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 18.0638
Epoch 56/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 17.9085
Epoch 57/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 17.7533
Epoch 58/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 17.5981
Epoch 59/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 17.4430
Epoch 60/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 17.2880
Epoch 61/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 17.1331
Epoch 62/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 16.9784
Epoch 63/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 16.8237
Epoch 64/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 16.6692
Epoch 65/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 16.5149
Epoch 66/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 16.3607
Epoch 67/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 16.2067
Epoch 68/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 16.0529
Epoch 69/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 15.8993
Epoch 70/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 15.7460
Epoch 71/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 15.5929
Epoch 72/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 15.4401
Epoch 73/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 15.2875
Epoch 74/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 15.1353
Epoch 75/75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 14.9833

In [75]:
# Check updated weights after training
model.get_weights()

[array([[0.22275329, 0.22275329],
        [0.22471388, 0.22471388]], dtype=float32),
 array([0.12616633, 0.12616633], dtype=float32),
 array([[0.22434117],
        [0.22434117]], dtype=float32),
 array([0.11508986], dtype=float32)]

In [78]:
model.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

array([[1.7778634],
       [1.7787431],
       [1.7796228],
       [1.8813276]], dtype=float32)